---
- hosts: app 
  gather_facts: true
  vars_files:
    - ~/ansible/inventory.yml
  vars:
    packets_ubuntu: ["aptitude", "ca-certificates", "curl", "software-properties-common"]
    packets_centos: ["ca-certificates", "curl", "yum-utils"]
  become: true  
  tasks:
    - name: Install required system packages ubuntu
      apt: name="{{ item }}" state=latest update_cache=yes
      loop: "{{ packets_ubuntu }}"
      when: ansible_distribution == "Ubuntu" 
    - name: Install required system packages centos
      yum: name="{{ item }}" state=latest update_cache=yes
      loop: ["{{ packets_centos }}"]
      when: ansible_distribution == "CentOS"
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == "Ubuntu" 
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ansible_distribution == "Ubuntu"  
    - name: Install docker-ce ubuntu
      apt: update_cache=yes name=docker-ce state=latest
      when: ansible_distribution == "Ubuntu"
    - name: Install docker-ce centos
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      package:
        name: docker-ce
        state: latest
      when: ansible_distribution == "CentOS"  
    - name: start docker
      service: name=docker state=started
    
- hosts: database
  vars_files:
    - ~/ansible/inventory.yml
  vars:
    db_user: sf_test
    db_name: test
    db_password: sf_test
    packets_db: ["postgresql", "postgresql-contrib", "libpq-dev", "python3-psycopg2"]
  become: true
  tasks:
    - name: install postgresql
      apt: name="{{ item }}" update_cache=true state=latest
      loop: "{{packets_db}}"
    - name: start postgresql_service
      service: name=posgresql state=started
    - name: Create the database specified in vars
       become: true
    become_user: postgres
     postgresql_db: name={{ db_name }}
          template="template0"
          state=present
    - name: Ensure user has access to the new database
     become: true
     become_user: postgres
     postgresql_user: db={{ db_name }}
          name={{ db_user }}
          password={{ db_password }}
          priv=ALL
          state=present
    - name: Ensure user does not have unnecessary permissions
     become: true
     become_user: postgres
     postgresql_user: name={{ db_user }}
          role_attr_flags=NOSUPERUSER,NOCREATEDB
          state=present
