---
- hosts: app 
  gather_facts: true
  vars_files:
    - ~/ansible/inventory.yml
  vars:
    packets_ubuntu: ["aptitude", "ca-certificates", "curl", "software-properties-common"]
    packets_centos: ["ca-certificates", "curl", "yum-utils"]
  become: true  
  tasks:
    - name: Install required system packages ubuntu
      apt: name="{{ item }}" state=latest update_cache=yes
      loop: "{{ packets_ubuntu }}"
      when: ansible_distribution == "Ubuntu" 
    - name: Install required system packages centos
      yum: name="{{ item }}" state=latest update_cache=yes
      loop: ["{{ packets_centos }}"]
      when: ansible_distribution == "CentOS"
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == "Ubuntu" 
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ansible_distribution == "Ubuntu"  
    - name: Install docker-ce ubuntu
      apt: update_cache=yes name=docker-ce state=latest
      when: ansible_distribution == "Ubuntu"
    - name: Install docker-ce centos
      
      yum: name=docker-ce state=latest update_cache=yes
      when: ansible_distribution == "CentOS"  
    - name: start docker
      service: name=docker state=started
    
- hosts: database
  vars_files:
    - ~/ansible/inventory.yml
  become: true
  tasks:
    - name: install postgresql
      apt: name=postgresql state=latest update_cache=yes
    - name: start postgresql_service
      service: name=posgresql state=started
